---
layout: post
title:  "Week 13, Day 50"
date:   2020-09-22 007:52:44 -0600
categories: jekyll update
---

## Standup

### Past week and a half
Zach's funeral, visiting in Illinois
  
### Today
* Sean is having Mac issues, Andrew C is having AIDE issues
* Catch up
* Saving defect
* Other defects

### Tomorrow
* Same
  
### Impediments
* AIDE issues, Mac issues
  
### From other teammates


### What I actually ended up doing
Debugging for PEN-4391- VETGEN-UI: App crashes when saving scenario
* If an empty list is passed in, the app will not crash, but the Scenarios are not repopulated - If you close out the tool and re-run it, the saved Scenario is there.
* Need to figure out what to pass in to correctly repopulate the scenarios

* Uncovered possible additional defect with saving:
  * Click the + (New Scenario) button
  * Services-Operations List should be empty
  * Enter a filename to save, click the save icon
  * Tool returns to empty home screen
  * Close tool
  * Re-run tool
  * Click Edit Scenario button of the saved scenario
  * Scenario has n copies of default scenario Services-Operations (expected Service-Operations list to be empty from initial save point)

* Uncovered possible new defect with saving:
  * saving a previously saved scenario without adding additional services-operations causes Vetgen-UI to crash
    * Crash Log:
      * Traceback (most recent call last):
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen.py", line 41, in <module>
     VetGen().run()
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/base.py", line 342, in idle
     self.dispatch_input()
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/base.py", line 327, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/base.py", line 293, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivymd/uix/behaviors/ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivymd/uix/button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/vetgen/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/UI/Screens/newscenario.py", line 275, in save_scenario
     self.save_input.text, self.current_edited_scenario_operations
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/UI/Screens/screenmanager.py", line 107, in save_scenario
     override_value_sets=override_value_sets,
   File "/Users/lefant/Desktop/Desktop - le'fant’s MacBook Pro/testgen-ui-master2/testgen-ui/scenariohandler.py", line 265, in new_scenario
     self.delete_scenario(self.scenarios[found_scenario_index])
 IndexError: list index out of range
  * adds additional services-operations to the list 

EOD:
Worked on PEN-4391- VETGEN-UI: App crashes when saving scenario. Passed in an empty list into the repopulate_scenarios() call (screenmanager.py line #110) which allows user to save a new scenario without the app crashing, but takes the user back to a blank home screen (effectively does not repopulate the home screen). If you close/re-run the tool, the saved scenario is present in the list of scenarios, but with added Services/Operations in the list. Ran into some unexpected behaviors when editing a previously saved scenario as well, but main focus is on fixing PEN-4391.

### TO LEARN
  
### //TODO

### Daily Workflow
* Login
* Update/Setup Weekly Blog Posts
* Open Jira
* Check lefant email
* Check BAH email
* Check VA email
* Connect to Tunnel (if necessary)
* Open GitHub Desktop
* Open VS Code
  
### Issues
* Having issues with my TimeMachine backup on my iMac
